version: '3.9'

networks:
  niko-network:
    driver: bridge

volumes:
  mysql-data:

services:
  api:
    build: .
    restart: always
    container_name: niko-api
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    ports:
      - 3333:3000
    volumes:
      - ./src:/app/src
      - ./.env:/app/.env
    environment:
      APP_PORT: 3000
      DB_MAIN_HOST: db
      DB_MAIN_PORT: 3306
      REDIS_HOST: redis
      REDIS_PORT: 6379
    command: yarn start:dev
    networks:
      - niko-network

  db:
    image: mysql:5.7
    restart: always
    container_name: niko-db
    environment:
      MYSQL_ROOT_PASSWORD: qjoyfiFFO6OUhegdLBTiLg
      MYSQL_DATABASE: niko
      TZ: America/Sao_Paulo
    ports:
      - 3309:3306
    volumes:
      - mysql-data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - niko-network
    healthcheck:
      test:
        [
          'CMD',
          'mysqladmin',
          'ping',
          '-h',
          'localhost',
          '-u',
          'root',
          '-p$$MYSQL_ROOT_PASSWORD',
        ]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    container_name: niko-redis
    image: redis:7-bullseye
    ports:
      - 6379:6379
    volumes:
      - /redis_niko_data:/data
    networks:
      - niko-network
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 10s
      timeout: 5s
      retries: 5
