version: '3.9'

networks:
  niko-network:
    driver: bridge

volumes:
  mysql-data:

services:
  api:
    build: .
    restart: always
    container_name: niko-api
    depends_on:
      - db
      - redis
    ports:
      - 3333:3000
    volumes:
      - ./src:/usr/niko/src
      - ./.env:/usr/niko/.env
    environment:
      APP_PORT: 3000
      DB_MAIN_HOST: db
      DB_MAIN_PORT: 3306
      REDIS_HOST: redis
      REDIS_PORT: 6379
    command: yarn start:dev
    networks:
      - niko-network

  db:
    image: mysql:5.7
    restart: always
    container_name: niko-db
    environment:
      MYSQL_ROOT_PASSWORD: qjoyfiFFO6OUhegdLBTiLg
      MYSQL_DATABASE: niko
    ports:
      - 3309:3306
    volumes:
      - mysql-data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - niko-network

  redis:
    container_name: niko-redis
    image: redis:7-bullseye
    ports:
      - 6379:6379
    volumes:
      - /redis_niko_data:/data
    networks:
      - niko-network
