export enum EventBatchHistory {
  ATRIBUICAO = 'ATRIBUIÇÃO',
  REMOCAO_ATRIBUICAO = 'REMOÇÃO_ATRIBUIÇÃO',
  OBSERVACAO = 'OBSERVAÇÃO',
  CADASTRO = 'CADASTRO',
  EDICAO = 'EDIÇÃO',
  EDICAO_STATUS_PRINCIPAL = 'EDIÇÃO_STATUS_PRINCIPAL',
}
