export const MIN_USERNAME_CHARACTERS = 6;
export const MIN_SETTLEMENT_PROJECT_NAME_CHARACTERS = 3;
export const MIN_BATCH_OBSERVATION_CHARACTERS = 3;
export const MIN_ROLE_NAME_CHARACTERS = 3;
export const MIN_ROLE_DESCRIPTION_CHARACTERS = 3;
export const MIN_PERMISSION_NAME_CHARACTERS = 3;
export const MIN_PERMISSION_DESCRIPTION_CHARACTERS = 3;
export const MAX_USERS_ASSIGN_TO_BATCH = 5;
